name: Android CI

on:
  push:
  workflow_dispatch:
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Rename, Restyle, and Update Package Name
        run: |
          find . -name "strings.xml" -exec sed -i 's/<string name="app_short_name">MJLauncher<\/string>/<string name="app_short_name">Obsidian Launcher<\/string>/gI' {} +
          find . -name "strings.xml" -exec sed -i 's/MojoLauncher/Obsidian Launcher/gI' {} +
          find . -name "strings.xml" -exec sed -i 's/PojavLauncher/Obsidian Launcher/gI' {} +
          find . -name "strings.xml" -exec sed -i 's/MJLauncher/Obsidian Launcher/gI' {} +
          find . -type f -exec sed -i 's/git.artdeell.mjlaunch/com.obsidian.launcher/g' {} +
          find . -type f -exec sed -i 's/git\.artdeell\.mjlaunch/com\.obsidian\.launcher/g' {} +
          
          find . -name "strings.xml" -exec sed -i 's/https:\/\/discord.gg\/VHdwQFsaGX/https:\/\/discord.gg\/fvXrtb9kja/g' {} +
          
          sed -i 's/<color name="background_app">#181818<\/color>/<color name="background_app">#000000<\/color>/gI' app_pojavlauncher/src/main/res/values/colors.xml
          sed -i 's/<color name="background_bottom_bar">#232323<\/color>/<color name="background_bottom_bar">#000000<\/color>/gI' app_pojavlauncher/src/main/res/values/colors.xml
          sed -i 's/<color name="background_status_bar">#242424<\/color>/<color name="background_status_bar">#000000<\/color>/gI' app_pojavlauncher/src/main/res/values/colors.xml
          
          sed -i 's/#91dffb/#D32F2F/gI' app_pojavlauncher/src/main/res/values/colors.xml
          sed -i 's/#464646/#2A0000/gI' app_pojavlauncher/src/main/res/values/colors.xml

          find app_pojavlauncher/src/main/res/ -name "ic_mojo_full.webp" -delete
          
          for dir in app_pojavlauncher/src/main/res/mipmap-*; do
            res_type=$(basename "$dir")
            if [ -f "app_pojavlauncher/src/main/res/$res_type/ic_launcher.png" ]; then
              cp "app_pojavlauncher/src/main/res/$res_type/ic_launcher.png" "app_pojavlauncher/src/main/res/drawable/ic_mojo_full.png"
              break
            fi
          done
          
          if [ ! -f "app_pojavlauncher/src/main/res/drawable/ic_mojo_full.png" ]; then
            cp app_pojavlauncher/src/main/res/mipmap-hdpi/ic_launcher.png app_pojavlauncher/src/main/res/drawable/ic_mojo_full.png || true
          fi

      - name: Get LTW
        uses: dawidd6/action-download-artifact@v6
        continue-on-error: true
        with:
          repo: MojoLauncher/LTW
          workflow: android.yml
          workflow_conclusion: success
          name: output-aar
          path: app_pojavlauncher/libs

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.14.3"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Create out directory
        run: mkdir out

      - name: Build Debug .apk
        run: |
          gradle :app_pojavlauncher:assembleFullDebug
          mv app_pojavlauncher/build/outputs/apk/full/debug/app_pojavlauncher-full-debug.apk out/ObsidianLauncher-debug.apk

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: ObsidianLauncher-debug
          path: out/ObsidianLauncher-debug.apk
